apiVersion: v1
data:
  ARGO_CD_URL: xxxxxxxxxx
  ARGO_WORKFLOWS_URL: xxxxxxxxxx
  ARGOCD_AUTH_TOKEN: xxxxxxxxxx
  BACKSTAGE_FRONTEND_URL: xxxxxxxxxx
  KEYCLOAK_CLIENT_SECRET: xxxxxxxxxx
  KEYCLOAK_NAME_METADATA: xxxxxxxxxx
  POSTGRES_HOST: xxxxxxxxxx
  POSTGRES_PASSWORD: 
  POSTGRES_PORT: xxxxxxxxxx
  POSTGRES_USER: xxxxxxxxxx
kind: Secret
metadata:
  name: backstage-env-vars
type: Opaque
